import { useState, useRef } from 'react'
import { useMsal } from '@azure/msal-react'
import { useApi } from '../hooks/useApi'
import { getDisplayName, getSignInEmail, parseAccessTokenClaims, apiTokenRequest } from '../auth/msalConfig'

// ---------------------------------------------------------------------------
// ActivationScreen — shown when an authenticated user is not yet enrolled
// in any family. They enter an 8-character invite code (generated by a super
// admin) to link their account to a family with a specific role.
//
// Security:
//   - Code is submitted to /api/invite/redeem with the MSAL Bearer token
//   - familyId and role are assigned server-side from the invite record
//   - Client never controls what family or role is assigned
//   - Code input is normalised to lowercase before submission
// ---------------------------------------------------------------------------

interface Props {
  /** Called after successful redemption — parent should reload app state. */
  onEnrolled: () => void
}

interface RedeemErrorBody {
  code?: string
  message?: string
}

// Maps server error codes to user-friendly messages
const ERROR_MESSAGES: Record<string, string> = {
  INVALID_CODE:     'That code doesn\'t exist. Double-check it and try again.',
  CODE_USED:        'That code has already been used. Ask your admin to generate a new one.',
  CODE_EXPIRED:     'That code has expired. Ask your admin to generate a new one.',
  ALREADY_ENROLLED: 'This account is already enrolled in a family.',
}

export default function ActivationScreen({ onEnrolled }: Props) {
  const { accounts, instance } = useMsal()
  const { apiFetch } = useApi()

  const account = accounts[0]

  // Pre-populate from the ?invite= query param (present when the user clicked
  // an emailed invite link before authenticating — MSAL preserves the URL via
  // redirectStartPage so the param survives the login redirect).
  const urlInviteCode = (() => {
    const raw = new URLSearchParams(window.location.search).get('invite') ?? ''
    return raw.toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 8)
  })()

  const [code, setCode]               = useState(urlInviteCode)
  const [submitting, setSubmitting]   = useState(false)
  const [error, setError]             = useState<string | null>(null)
  const codeRef = useRef<HTMLInputElement>(null)

  const handleSignOut = () => {
    instance.logoutRedirect({ account }).catch(console.error)
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setError(null)

    const trimmedCode = code.trim().toLowerCase()

    // Client-side validation before sending
    if (!/^[a-z0-9]{8}$/.test(trimmedCode)) {
      setError('Invite codes are 8 characters (letters and numbers). Check your code and try again.')
      codeRef.current?.focus()
      return
    }

    setSubmitting(true)
    try {
      // The "First Name" / "Last Name" custom attributes are now emitted
      // directly in the ID token, so getDisplayName() will resolve them
      // without needing the access token. We still attempt to acquire the
      // access token as a belt-and-suspenders fallback (e.g. for accounts
      // that pre-date the custom attribute migration, which may still carry
      // given_name/family_name only in the AT).
      let resolvedName = getDisplayName(account).trim()
      try {
        const tokenResult = await instance.acquireTokenSilent({ ...apiTokenRequest, account })
        const atClaims = parseAccessTokenClaims(tokenResult.accessToken)
        const nameFromAt = getDisplayName(account, atClaims).trim()
        if (nameFromAt) resolvedName = nameFromAt
      } catch {
        // Non-fatal — proceed with whatever we already have from the ID token
      }

      // Safety truncation to stay within the API's 60-char limit
      resolvedName = resolvedName.slice(0, 60)

      if (!resolvedName) {
        setError('Your name could not be determined from your account. Please sign out and sign in again.')
        setSubmitting(false)
        return
      }

      await apiFetch('invite/redeem', {
        method: 'POST',
        body: JSON.stringify({ code: trimmedCode, displayName: resolvedName }),
      })
      // Success — parent reloads the app to pick up the new user record
      onEnrolled()
    } catch (err: unknown) {
      // Try to extract structured error from the API response
      const apiErr = err as { status?: number; body?: RedeemErrorBody }
      const serverCode = apiErr?.body?.code ?? ''
      const message = ERROR_MESSAGES[serverCode]
        ?? apiErr?.body?.message
        ?? 'Something went wrong. Please try again.'
      setError(message)
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="activation-screen">
      <div className="activation-card">
        <div className="activation-card__icon">🎉</div>
        <h1 className="activation-card__title">Welcome to Allowance!</h1>
        <p className="activation-card__hint">
          Enter the invite code you received to join your family and get started.
        </p>

        <form onSubmit={handleSubmit} autoComplete="off" noValidate>
          <div className="sa-form-group" style={{ marginBottom: 24 }}>
            <label className="sa-form-label" htmlFor="act-code">Invite code</label>
            <input
              id="act-code"
              ref={codeRef}
              className="sa-form-input activation-card__code-input"
              type="text"
              value={code}
              onChange={e => setCode(e.target.value.toLowerCase().replace(/[^a-z0-9]/g, ''))}
              placeholder="8-character code"
              maxLength={8}
              spellCheck={false}
              autoCorrect="off"
              autoCapitalize="none"
              autoFocus
              required
            />
          </div>

          {error && (
            <p className="sa-form-error" role="alert" style={{ marginBottom: 16 }}>
              {error}
            </p>
          )}

          <button
            className="btn btn--primary"
            type="submit"
            disabled={submitting}
            style={{ width: '100%' }}
          >
            {submitting ? 'Activating…' : 'Activate Account'}
          </button>
        </form>

        <hr style={{ margin: '24px 0', borderColor: 'var(--border)' }} />
        <p style={{ fontSize: '0.8rem', color: '#64748b', textAlign: 'center' }}>
          Signed in as {getSignInEmail(account)}{' '}
          <button className="sa-link" type="button" onClick={handleSignOut}>(sign out)</button>
        </p>
      </div>
    </div>
  )
}
